### ISSUE TITLE
ImportError HostOnlyCUDAMemoryManager when importing cudf

### ISSUE THREAD

**Issue by JulianWgs** [rapidsai/rapidsai-csp-utils#27] opened 2020-07-01 10:04 UTC
I'm getting this error when installing cudf 0.14 on Google Colab.

I supposed cudf 0.14 is only compatible with numba 0.49 and above, because `HostOnlyCUDAMemoryManager` was introduced in that version. I could't test that yet.

Then a change [here](https://github.com/rapidsai/cudf/blob/4e5401e6073b89119c410e5af14b718959760baf/python/cudf/setup.py#L14) would also be necassary.

```python
/usr/local/lib/python3.6/dist-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/usr/local/lib/python3.6/dist-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice/.

For more information about alternatives visit: ('http://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-3-e13365c50bc4> in <module>()
----> 1 import cudf

2 frames

/usr/local/lib/python3.6/site-packages/cudf/__init__.py in <module>()
      8 from numba import cuda
      9 
---> 10 import rmm
     11 
     12 from cudf import core, datasets

/usr/local/lib/python3.6/site-packages/rmm/__init__.py in <module>()
     15 import weakref
     16 
---> 17 from rmm.rmm import (
     18     RMMError,
     19     RMMNumbaManager,

/usr/local/lib/python3.6/site-packages/rmm/rmm.py in <module>()
     18 import numpy as np
     19 from numba import cuda
---> 20 from numba.cuda import HostOnlyCUDAMemoryManager, IpcHandle, MemoryPointer
     21 
     22 import rmm._lib as librmm

ImportError: cannot import name 'HostOnlyCUDAMemoryManager'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by taureandyernv** [comment] 2020-07-01 19:00
@JulianWgs can you send me your `conda list`.  i'll check too.

**Comment by JulianWgs** [comment] 2020-07-01 21:04
Thanks for the fast response! I just reproduced the issue with a fresh Tesla T4 instance.

```
# packages in environment at /usr/local:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
arrow-cpp                 0.15.0           py36h090bef1_2    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     2.1.1            py36h9f0ad1d_0    conda-forge
boost                     1.70.0           py36h9de70de_1    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1002    conda-forge
brotlipy                  0.7.0           py36h8c4c3a4_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachetools                4.1.1                      py_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4           py36h9f0ad1d_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
conda                     4.8.3            py36h9f0ad1d_1    conda-forge
conda-package-handling    1.6.0            py36h8c4c3a4_2    conda-forge
contextvars               2.4                        py_0    conda-forge
cryptography              2.9.2            py36h45558ae_0    conda-forge
cudatoolkit               10.1.243             h6bb024c_0    nvidia
cudf                      0.14.0                   py36_0    rapidsai/label/main
cudnn                     7.6.0                cuda10.1_0    nvidia
cugraph                   0.14.0                   py36_0    rapidsai/label/main
cuml                      0.14.0          cuda10.1_py36_0    rapidsai/label/main
cupy                      7.6.0            py36h5c369b2_0    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cusignal                  0.14.0                   py36_0    rapidsai/label/main
cuspatial                 0.14.0                   py36_0    rapidsai/label/main
cytoolz                   0.10.1           py36h516909a_0    conda-forge
dask                      2.19.0                     py_0    conda-forge
dask-core                 2.19.0                     py_0    conda-forge
dask-cudf                 0.14.0                   py36_0    rapidsai/label/main
decorator                 4.4.2                      py_0    conda-forge
distributed               2.19.0           py36h9f0ad1d_0    conda-forge
dlpack                    0.3                  he1b5a44_0    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastavro                  0.23.5           py36h8c4c3a4_0    conda-forge
fastrlock                 0.5              py36h831f99a_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.7.4                      py_0    conda-forge
gcsfs                     0.6.2                      py_0    conda-forge
gdal                      3.0.2            py36hbb6b9fb_2    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.65.0               h3eb4bd4_0  
glog                      0.4.0                h49b9bf7_3    conda-forge
google-auth               1.17.2                     py_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
immutables                0.14             py36h8c4c3a4_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json-c                    0.13.1            hbfbb72e_1002    conda-forge
kealib                    1.4.13               hec59c27_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcudf                   0.14.0               cuda10.1_0    rapidsai/label/main
libcugraph                0.14.0               cuda10.1_0    rapidsai/label/main
libcuml                   0.14.0               cuda10.1_0    rapidsai/label/main
libcumlprims              0.14.1               cuda10.1_0    nvidia
libcurl                   7.68.0               hda55be3_0    conda-forge
libcuspatial              0.14.0               cuda10.1_0    rapidsai/label/main
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20191231         h7b6447c_0  
libevent                  2.1.10               hcdb4288_1    conda-forge
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.2                hc7cfd23_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libhwloc                  2.1.0                h3c4fd83_0    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
libnvstrings              0.14.0               cuda10.1_0    rapidsai/label/main
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libpq                     11.5                 hd9ab2ff_2    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.14.0               cuda10.1_0    rapidsai/label/main
libspatialite             4.3.0a            h4f6d029_1032    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxgboost                1.1.0dev.rapidsai0.14      cuda10.1_0    rapidsai/label/main
libxml2                   2.9.10               hee79883_0    conda-forge
llvmlite                  0.32.1           py36hfa65bc7_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py36h8c4c3a4_1    conda-forge
msgpack-python            1.0.0            py36hdb11119_1    conda-forge
nccl                      2.5.7.1              h51cf6c1_0    conda-forge
ncurses                   6.2                  he6710b0_1  
numba                     0.49.1           py36h0573a6f_0  
numpy                     1.18.5           py36h7314795_0    conda-forge
nvstrings                 0.14.0                   py36_0    rapidsai/label/main
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    0.25.3           py36hb3f55d8_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    7.1.2            py36h8328e55_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_2    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
psutil                    5.7.0            py36h8c4c3a4_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py-xgboost                1.1.0dev.rapidsai0.14  cuda10.1py36_0    rapidsai/label/main
pyarrow                   0.15.0           py36h8b68381_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.3           py36h8c4c3a4_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pynvml                    8.0.4                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py36h9f0ad1d_1    conda-forge
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py36h8c4c3a4_0    conda-forge
re2                       2020.04.01           he1b5a44_0    conda-forge
readline                  8.0                  h7b6447c_0  
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
rmm                       0.14.0                   py36_0    rapidsai/label/main
rsa                       4.6                pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py36h8c4c3a4_1001    conda-forge
scikit-learn              0.23.1           py36h0e1014b_0    conda-forge
scipy                     1.5.0            py36h2d22cac_0    conda-forge
setuptools                47.3.1           py36h9f0ad1d_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
spdlog                    1.6.1                hc9558a2_0    conda-forge
sqlite                    3.32.3               h62c20be_0  
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tiledb                    1.6.2                h7d710e0_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
tqdm                      4.47.0             pyh9f0ad1d_0    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
tzcode                    2020a                h516909a_0    conda-forge
ucx                       1.8.0+gf6ec8d4      cuda10.1_20    rapidsai/label/main
ucx-py                    0.14.0+gf6ec8d4          py36_0    rapidsai/label/main
uriparser                 0.9.3                he1b5a44_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xgboost                   1.1.0dev.rapidsai0.14  cuda10.1py36_0    rapidsai/label/main
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```

**Comment by taureandyernv** [comment] 2020-08-13 03:16
I keep trying so hard to reproduce this... @JulianWgs

**Comment by taureandyernv** [comment] 2021-01-22 18:30
closing as 1) couldn't reproduce it and 2) colab is pegged at a "working" version of 0.14 until #28 is solved somehow.  Until then @JulianWgs , you can try app.blazingsql.com's instance if you are continuing to have problems.

**Closed by taureandyernv** 2021-01-22 18:30 UTC
